openapi: 3.0.3
info:
  title: The SpatioTemporal Asset Catalog API - Filter
  description: Adds parameters to compare properties and only return the items that match
  version: 1.0.0-beta.1

paths:
  /queryables:
    get:
      summary: Get the JSON Schema defining the list of variable terms that can be used in CQL expressions.
      operationId: getQueryables
      description: |-
        This endpoint returns a list of variable terms that can be used in CQL expressions. The
        precise definition of this can be found in the OGC API - Features - Part 3: Filtering and the 
        Common Query Language (CQL) specification.
      tags:
        - Queryables
      # parameters:
      # todo: may have collections parameter in the future
      responses: 
        '200':
          description: A JSON Schema defining the Queryables
          content:
            application/schema+json:
              schema:
                $ref: '' # TBD
        default:
          $ref: '../core/commons.yaml#/components/responses/Error'
components:
  parameters:
    filter:
      name: filter
      x-stac-api-fragment: filter
      in: query
      description: |-
        **Extension:** Filter
      
        A filter for properties in Items.
      required: true
      schema:
        type: string
    filter-lang:
      name: filter-lang
      x-stac-api-fragment: filter
      in: query
      description: |-
        **Extension:** Filter
      
        The Filter Language using in the text in the filter parameter. Must be one of 'cql-text' or 'cql-json'.
      required: false
      schema:
        type: string
    filter-crs:
      name: filter-crs
      x-stac-api-fragment: filter
      in: query
      description: |-
        **Extension:** Filter
      
        The CRS used by spatial predicates in the filter parameter. In STAC API, only value that must be accepted
        is 'http://www.opengis.net/def/crs/OGC/1.3/CRS84'.
      required: false
      schema:
        type: string
  schemas:
    searchBody:
      type: object
      x-stac-api-fragment: filter
      description: |-
        **Optional Extension:** Filter

        A filter for properties in Items.      
      properties:
        filter:
          $ref: '#/components/schemas/filter'
        filter-lang:
          $ref: '#/components/schemas/filter-lang'
        filter-crs:
          $ref: '#/components/schemas/filter-crs'
    filter:
      description: |
        TBD
      type: object
    filter-lang:
      description: |
        TBD
      type: string
      enum: 
        - 'cql-text'
        - 'cql-json'
    filter-crs:
      description: |
        TBD
      type: string