# Adds sorting parameter to the base STAC search.
paths:
  /search:
    get:
      parameters:
        - $ref: '#/components/parameters/sortby'
components:
  parameters:
    sortby:
      name: sortby
      in: query
      description: |-
        An array of property names, prefixed by either "+" for ascending or
        "-" for descending. If no prefix is provided, "+" is assumed.
      required: false
      schema:
        type: string
        example: '+id,-properties.eo:cloud_cover'
      style: form
      explode: false
  schemas:
    searchBody:
      allOf:
        - $ref: '#/components/schemas/sortFilter'
    sortFilter:
      type: object
      description: Sort the results
      properties:
        sortby:
          $ref: '#/components/schemas/sortby'
    sortby:
      type: array
      description: |
        An array of objects containing a property name and sort direction.
      minItems: 1
      items:
        type: object
        required:
          - field
          - direction
        properties:
          field:
            type: string
          direction:
            type: string
            default: asc
            enum:
              - asc
              - desc
      example:
        - field: properties.eo:cloud_cover
          direction: asc
        - field: id
          direction: desc
